[package]
name = "kairos"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

[addresses]
kairos = "0x0"

[environments]
devnet = "082d5a13"
